"""second

Revision ID: 28e14335c8cf
Revises: 54c97ca48622
Create Date: 2023-07-03 19:28:13.330926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e14335c8cf'
down_revision = '54c97ca48622'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
