"""third

Revision ID: 738fa3ebe6e9
Revises: 28e14335c8cf
Create Date: 2023-07-03 19:34:02.875556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738fa3ebe6e9'
down_revision = '28e14335c8cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
